package constant

const CROSSOVER_METHOD_ROW string = "CROSSOVER_METHOD_ROW"
const CROSSOVER_METHOD_COLUMN string = "CROSSOVER_METHOD_COLUMN"
const CROSSOVER_METHOD_SECTION string = "CROSSOVER_METHOD_SECTION"
